name: Rust

on:
  push:
    branches: [ "main", "temp" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly

    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    
    - name: Install llvm-cov
      run: cargo +stable install cargo-llvm-cov --locked

    - name: Run tests and generate coverage data
      run: |
        cargo build
        cargo test
        cargo llvm-cov --lcov --output-path lcov.info

    - uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        verbose: true
