name: Rust

on:
  push:
    branches: [ "main", "temp" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly

    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Install llvm-tools-preview and cargo-binutils
      run: |
        rustup component add llvm-tools-preview
        rustup component add rust-src
        cargo install cargo-binutils

    - name: Run tests and generate coverage data
      run: |
        export RUSTFLAGS="-Cinstrument-coverage"
        cargo build
        cargo test
        cargo cov -- show \
          --use-color \
          --ignore-filename-regex='/.cargo/registry' \
          --Xdemangler=rustfilt \
          --instr-profile=default.profdata \
          --summary-only \
          --output-path lcov.info

    - uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        verbose: true
