name: Rust

on:
  push:
    branches: [ "main", "temp" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly

    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run tests with coverage
      run: |
        cargo tarpaulin --out Xml
      continue-on-error: true
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: target/tarpaulin/coverage.xml

    - name: Generate coverage badge
      run: |
        wget https://github.com/codecov/codecov-bash/releases/latest/download/codecov
        chmod +x codecov
        ./codecov
